baseurl = "https://chris-prener.github.io/presentingData/"
languageCode = "en-us"
title = "Presenting Data"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Christopher Prener"
	description = "A Presentation Style Guide for the Social Sciences"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []
	
	# Ignore files
	ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = ""
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**presenting data** </br>a presentation style guide </br>for social science students"
		# The icons will be shown if you enter your username
		twitter = "chrisprener"
		github = "chris-prener"
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""
		# homepage url
		home="https://chris-prener.github.io/"

		copyright = [
			"&copy; 2018 [CC-BY-SA 4.0](/presentingData/license)",
			"Design: [HTML5 UP](//html5up.net)",
			"Cover Image: [M. Alizade](https://unsplash.com/@mohamadaz?utm_medium=referral)"
		]

  [params.avatar]
    hide = true

	[params.about]
		hide  = false
		title = "motivation"
		content = "Each year, I speak with both undergraduate and Master's students in [Sociology](https://www.slu.edu/arts-and-sciences/sociology-anthropology) at [Saint Louis University](https://www.slu.edu/) on presenting research. A public presentation, whether it is a capstone project, a Master's thesis, or a guest lecture, can be daunting for students. My goal is to help students develop skills for high quality, effective presentations. This site catalogues material related to both my undergraduate and graduate 'presentations on presentations' and provides resources for students on presentation design."


	[params.portfolio]
		hide  = false
		title = "primary resources"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Undergraduate Slides"
			description = "Fall 2017 Capstone Course Presentation ([more](/presentingData/undergrad))"

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Master's Slides"
			description = "Fall 2017 Pro-Seminar Presentation ([more](/presentingData/graduate))"

    [[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Presentation Resources"
			description = "Articles and tools referenced in slides ([more](/presentingData/resources))"

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Sequoia Keynote Theme"
			description = "Theme used for most of my teaching and presenting ([more](/presentingData/sequoia))"

	[params.recentposts]
		hide  = true
		title = "recent articles"

	[params.contact]
		hide  = true
		email = "chris.prener@slu.edu"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "articles"
	url  = "post/"
	weight = 12

[[menu.main]]
	name = "undergraduate slides"
	url  = "/undergrad"
	weight = 20
	
[[menu.main]]
	name = "master's slides"
	url  = "/graduate"
	weight = 21

[[menu.main]]
	name = "presentation resources"
	url  = "/resources"
	weight = 22

[[menu.main]]
	name = "sequoia template"
	url  = "/sequoia"
	weight = 23
	
[[menu.main]]
	name = "license"
	url  = "/license"
	weight = 45
